#include-once
#include "mediapipe_interface.au3"

; mediapipe::tasks::autoit::core::utils::MpStatus
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_OK = 0
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_CANCELLED = 1
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_UNKNOWN = 2
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_INVALID_ARGUMENT = 3
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_DEADLINE_EXCEEDED = 4
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_NOT_FOUND = 5
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_ALREADY_EXISTS = 6
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_PERMISSION_DENIED = 7
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_RESOURCE_EXHAUSTED = 8
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_FAILED_PRECONDITION = 9
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_ABORTED = 10
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_OUT_OF_RANGE = 11
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_UNIMPLEMENTED = 12
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_INTERNAL = 13
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_UNAVAILABLE = 14
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_DATA_LOSS = 15
Global Const $MEDIAPIPE_TASKS_AUTOIT_CORE_UTILS_MP_STATUS_MP_UNAUTHENTICATED = 16

; mediapipe::tasks::vision::face_landmarker::Blendshapes
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_NEUTRAL = 0
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_BROW_DOWN_LEFT = 1
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_BROW_DOWN_RIGHT = 2
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_BROW_INNER_UP = 3
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_BROW_OUTER_UP_LEFT = 4
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_BROW_OUTER_UP_RIGHT = 5
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_CHEEK_PUFF = 6
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_CHEEK_SQUINT_LEFT = 7
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_CHEEK_SQUINT_RIGHT = 8
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_BLINK_LEFT = 9
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_BLINK_RIGHT = 10
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_LOOK_DOWN_LEFT = 11
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_LOOK_DOWN_RIGHT = 12
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_LOOK_IN_LEFT = 13
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_LOOK_IN_RIGHT = 14
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_LOOK_OUT_LEFT = 15
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_LOOK_OUT_RIGHT = 16
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_LOOK_UP_LEFT = 17
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_LOOK_UP_RIGHT = 18
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_SQUINT_LEFT = 19
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_SQUINT_RIGHT = 20
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_WIDE_LEFT = 21
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_EYE_WIDE_RIGHT = 22
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_JAW_FORWARD = 23
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_JAW_LEFT = 24
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_JAW_OPEN = 25
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_JAW_RIGHT = 26
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_CLOSE = 27
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_DIMPLE_LEFT = 28
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_DIMPLE_RIGHT = 29
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_FROWN_LEFT = 30
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_FROWN_RIGHT = 31
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_FUNNEL = 32
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_LEFT = 33
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_LOWER_DOWN_LEFT = 34
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_LOWER_DOWN_RIGHT = 35
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_PRESS_LEFT = 36
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_PRESS_RIGHT = 37
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_PUCKER = 38
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_RIGHT = 39
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_ROLL_LOWER = 40
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_ROLL_UPPER = 41
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_SHRUG_LOWER = 42
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_SHRUG_UPPER = 43
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_SMILE_LEFT = 44
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_SMILE_RIGHT = 45
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_STRETCH_LEFT = 46
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_STRETCH_RIGHT = 47
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_UPPER_UP_LEFT = 48
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_MOUTH_UPPER_UP_RIGHT = 49
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_NOSE_SNEER_LEFT = 50
Global Const $MEDIAPIPE_TASKS_VISION_FACE_LANDMARKER_BLENDSHAPES_NOSE_SNEER_RIGHT = 51

; mediapipe::tasks::vision::hand_landmarker::HandLandmark
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_WRIST = 0
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_THUMB_CMC = 1
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_THUMB_MCP = 2
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_THUMB_IP = 3
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_THUMB_TIP = 4
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_INDEX_FINGER_MCP = 5
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_INDEX_FINGER_PIP = 6
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_INDEX_FINGER_DIP = 7
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_INDEX_FINGER_TIP = 8
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_MIDDLE_FINGER_MCP = 9
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_MIDDLE_FINGER_PIP = 10
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_MIDDLE_FINGER_DIP = 11
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_MIDDLE_FINGER_TIP = 12
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_RING_FINGER_MCP = 13
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_RING_FINGER_PIP = 14
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_RING_FINGER_DIP = 15
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_RING_FINGER_TIP = 16
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_PINKY_MCP = 17
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_PINKY_PIP = 18
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_PINKY_DIP = 19
Global Const $MEDIAPIPE_TASKS_VISION_HAND_LANDMARKER_HAND_LANDMARK_PINKY_TIP = 20

; mediapipe::tasks::vision::pose_landmarker::PoseLandmark
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_NOSE = 0
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_EYE_INNER = 1
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_EYE = 2
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_EYE_OUTER = 3
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_EYE_INNER = 4
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_EYE = 5
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_EYE_OUTER = 6
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_EAR = 7
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_EAR = 8
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_MOUTH_LEFT = 9
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_MOUTH_RIGHT = 10
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_SHOULDER = 11
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_SHOULDER = 12
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_ELBOW = 13
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_ELBOW = 14
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_WRIST = 15
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_WRIST = 16
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_PINKY = 17
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_PINKY = 18
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_INDEX = 19
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_INDEX = 20
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_THUMB = 21
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_THUMB = 22
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_HIP = 23
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_HIP = 24
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_KNEE = 25
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_KNEE = 26
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_ANKLE = 27
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_ANKLE = 28
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_HEEL = 29
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_HEEL = 30
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_LEFT_FOOT_INDEX = 31
Global Const $MEDIAPIPE_TASKS_VISION_POSE_LANDMARKER_POSE_LANDMARK_RIGHT_FOOT_INDEX = 32

; google::protobuf::Edition
Global Const $GOOGLE_PROTOBUF_EDITION_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_EDITION_LEGACY = 900
Global Const $GOOGLE_PROTOBUF_EDITION_PROTO2 = 998
Global Const $GOOGLE_PROTOBUF_EDITION_PROTO3 = 999
Global Const $GOOGLE_PROTOBUF_EDITION_2023 = 1000
Global Const $GOOGLE_PROTOBUF_EDITION_2024 = 1001
Global Const $GOOGLE_PROTOBUF_EDITION_1_TEST_ONLY = 1
Global Const $GOOGLE_PROTOBUF_EDITION_2_TEST_ONLY = 2
Global Const $GOOGLE_PROTOBUF_EDITION_99997_TEST_ONLY = 99997
Global Const $GOOGLE_PROTOBUF_EDITION_99998_TEST_ONLY = 99998
Global Const $GOOGLE_PROTOBUF_EDITION_99999_TEST_ONLY = 99999
Global Const $GOOGLE_PROTOBUF_EDITION_MAX = 0x7FFFFFFF

; google::protobuf::ExtensionRangeOptions::VerificationState
Global Const $GOOGLE_PROTOBUF_EXTENSION_RANGE_OPTIONS_DECLARATION = 0
Global Const $GOOGLE_PROTOBUF_EXTENSION_RANGE_OPTIONS_UNVERIFIED = 1

; google::protobuf::FieldDescriptorProto::Type
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_DOUBLE = 1
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_FLOAT = 2
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_INT64 = 3
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_UINT64 = 4
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_INT32 = 5
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_FIXED64 = 6
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_FIXED32 = 7
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_BOOL = 8
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_STRING = 9
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_GROUP = 10
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_MESSAGE = 11
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_BYTES = 12
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_UINT32 = 13
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_ENUM = 14
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_SFIXED32 = 15
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_SFIXED64 = 16
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_SINT32 = 17
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_TYPE_SINT64 = 18

; google::protobuf::FieldDescriptorProto::Label
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_LABEL_OPTIONAL = 1
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_LABEL_REPEATED = 3
Global Const $GOOGLE_PROTOBUF_FIELD_DESCRIPTOR_PROTO_LABEL_REQUIRED = 2

; google::protobuf::FileOptions::OptimizeMode
Global Const $GOOGLE_PROTOBUF_FILE_OPTIONS_SPEED = 1
Global Const $GOOGLE_PROTOBUF_FILE_OPTIONS_CODE_SIZE = 2
Global Const $GOOGLE_PROTOBUF_FILE_OPTIONS_LITE_RUNTIME = 3

; google::protobuf::FieldOptions::CType
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_STRING = 0
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_CORD = 1
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_STRING_PIECE = 2

; google::protobuf::FieldOptions::JSType
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_JS_NORMAL = 0
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_JS_STRING = 1
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_JS_NUMBER = 2

; google::protobuf::FieldOptions::OptionRetention
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_RETENTION_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_RETENTION_RUNTIME = 1
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_RETENTION_SOURCE = 2

; google::protobuf::FieldOptions::OptionTargetType
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_FILE = 1
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_EXTENSION_RANGE = 2
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_MESSAGE = 3
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_FIELD = 4
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_ONEOF = 5
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_ENUM = 6
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_ENUM_ENTRY = 7
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_SERVICE = 8
Global Const $GOOGLE_PROTOBUF_FIELD_OPTIONS_TARGET_TYPE_METHOD = 9

; google::protobuf::MethodOptions::IdempotencyLevel
Global Const $GOOGLE_PROTOBUF_METHOD_OPTIONS_IDEMPOTENCY_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_METHOD_OPTIONS_NO_SIDE_EFFECTS = 1
Global Const $GOOGLE_PROTOBUF_METHOD_OPTIONS_IDEMPOTENT = 2

; google::protobuf::FeatureSet::FieldPresence
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_FIELD_PRESENCE_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_EXPLICIT = 1
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_IMPLICIT = 2
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_LEGACY_REQUIRED = 3

; google::protobuf::FeatureSet::EnumType
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_ENUM_TYPE_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_OPEN = 1
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_CLOSED = 2

; google::protobuf::FeatureSet::RepeatedFieldEncoding
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_REPEATED_FIELD_ENCODING_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_PACKED = 1
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_EXPANDED = 2

; google::protobuf::FeatureSet::Utf8Validation
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_UTF8_VALIDATION_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_VERIFY = 2
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_NONE = 3

; google::protobuf::FeatureSet::MessageEncoding
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_MESSAGE_ENCODING_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_LENGTH_PREFIXED = 1
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_DELIMITED = 2

; google::protobuf::FeatureSet::JsonFormat
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_JSON_FORMAT_UNKNOWN = 0
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_ALLOW = 1
Global Const $GOOGLE_PROTOBUF_FEATURE_SET_LEGACY_BEST_EFFORT = 2

; google::protobuf::GeneratedCodeInfo::Annotation::Semantic
Global Const $GOOGLE_PROTOBUF_GENERATED_CODE_INFO_ANNOTATION_NONE = 0
Global Const $GOOGLE_PROTOBUF_GENERATED_CODE_INFO_ANNOTATION_SET = 1
Global Const $GOOGLE_PROTOBUF_GENERATED_CODE_INFO_ANNOTATION_ALIAS = 2

; mediapipe::LocationData::Format
Global Const $MEDIAPIPE_LOCATION_DATA_GLOBAL = 0
Global Const $MEDIAPIPE_LOCATION_DATA_BOUNDING_BOX = 1
Global Const $MEDIAPIPE_LOCATION_DATA_RELATIVE_BOUNDING_BOX = 2
Global Const $MEDIAPIPE_LOCATION_DATA_MASK = 3

; mediapipe::ImageFormat::Format
Global Const $MEDIAPIPE_IMAGE_FORMAT_UNKNOWN = 0
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGB = 1
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGBA = 2
Global Const $MEDIAPIPE_IMAGE_FORMAT_GRAY8 = 3
Global Const $MEDIAPIPE_IMAGE_FORMAT_GRAY16 = 4
Global Const $MEDIAPIPE_IMAGE_FORMAT_YCBCR420P = 5
Global Const $MEDIAPIPE_IMAGE_FORMAT_YCBCR420P10 = 6
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGB48 = 7
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGBA64 = 8
Global Const $MEDIAPIPE_IMAGE_FORMAT_VEC32F1 = 9
Global Const $MEDIAPIPE_IMAGE_FORMAT_VEC32F2 = 12
Global Const $MEDIAPIPE_IMAGE_FORMAT_VEC32F4 = 13
Global Const $MEDIAPIPE_IMAGE_FORMAT_LAB8 = 10
Global Const $MEDIAPIPE_IMAGE_FORMAT_SBGRA = 11

; cv::AccessFlag






; cv::Formatter::FormatType







; mediapipe::tasks::audio::core::RunningMode
Global Const $MEDIAPIPE_TASKS_AUDIO_CORE_AUDIO_CLIPS = 1
Global Const $MEDIAPIPE_TASKS_AUDIO_CORE_AUDIO_STREAM = 2

; mediapipe::tasks::core::HostEnvironment
Global Const $MEDIAPIPE_TASKS_CORE_HOST_ENVIRONMENT_UNKNOWN = 0
Global Const $MEDIAPIPE_TASKS_CORE_HOST_ENVIRONMENT_ANDROID = 1
Global Const $MEDIAPIPE_TASKS_CORE_HOST_ENVIRONMENT_IOS = 2
Global Const $MEDIAPIPE_TASKS_CORE_HOST_ENVIRONMENT_PYTHON = 3
Global Const $MEDIAPIPE_TASKS_CORE_HOST_ENVIRONMENT_WEB = 4

; mediapipe::tasks::core::HostSystem
Global Const $MEDIAPIPE_TASKS_CORE_HOST_SYSTEM_UNKNOWN = 0
Global Const $MEDIAPIPE_TASKS_CORE_HOST_SYSTEM_LINUX = 1
Global Const $MEDIAPIPE_TASKS_CORE_HOST_SYSTEM_MAC = 2
Global Const $MEDIAPIPE_TASKS_CORE_HOST_SYSTEM_WINDOWS = 3
Global Const $MEDIAPIPE_TASKS_CORE_HOST_SYSTEM_IOS = 4
Global Const $MEDIAPIPE_TASKS_CORE_HOST_SYSTEM_ANDROID = 5

; mediapipe::tasks::core::BaseOptions::Delegate
Global Const $MEDIAPIPE_TASKS_CORE_BASE_OPTIONS_CPU = 0
Global Const $MEDIAPIPE_TASKS_CORE_BASE_OPTIONS_GPU = 1
Global Const $MEDIAPIPE_TASKS_CORE_BASE_OPTIONS_EDGETPU_NNAPI = 2

; mediapipe::tasks::vision::core::RunningMode
Global Const $MEDIAPIPE_TASKS_VISION_CORE_IMAGE = 1
Global Const $MEDIAPIPE_TASKS_VISION_CORE_VIDEO = 2
Global Const $MEDIAPIPE_TASKS_VISION_CORE_LIVE_STREAM = 3

; mediapipe::tasks::vision::interactive_segmenter::RegionOfInterest::Format
Global Const $MEDIAPIPE_TASKS_VISION_INTERACTIVE_SEGMENTER_REGION_OF_INTEREST_FORMAT_UNSPECIFIED = 0
Global Const $MEDIAPIPE_TASKS_VISION_INTERACTIVE_SEGMENTER_REGION_OF_INTEREST_FORMAT_KEYPOINT = 1
Global Const $MEDIAPIPE_TASKS_VISION_INTERACTIVE_SEGMENTER_REGION_OF_INTEREST_FORMAT_SCRIBBLE = 2

; cv::UMatUsageFlags
