#include-once
#include "mediapipe_interface.au3"

; mediapipe::autoit::solutions::face_detection::FaceKeyPoint
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_FACE_DETECTION_FACE_KEY_POINT_RIGHT_EYE = 0
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_FACE_DETECTION_FACE_KEY_POINT_LEFT_EYE = 1
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_FACE_DETECTION_FACE_KEY_POINT_NOSE_TIP = 2
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_FACE_DETECTION_FACE_KEY_POINT_MOUTH_CENTER = 3
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_FACE_DETECTION_FACE_KEY_POINT_RIGHT_EAR_TRAGION = 4
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_FACE_DETECTION_FACE_KEY_POINT_LEFT_EAR_TRAGION = 5

; mediapipe::autoit::solutions::objectron::BoxLandmark
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_OBJECTRON_BOX_LANDMARK_CENTER = 0
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_OBJECTRON_BOX_LANDMARK_BACK_BOTTOM_LEFT = 1
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_OBJECTRON_BOX_LANDMARK_FRONT_BOTTOM_LEFT = 2
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_OBJECTRON_BOX_LANDMARK_BACK_TOP_LEFT = 3
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_OBJECTRON_BOX_LANDMARK_FRONT_TOP_LEFT = 4
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_OBJECTRON_BOX_LANDMARK_BACK_BOTTOM_RIGHT = 5
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_OBJECTRON_BOX_LANDMARK_FRONT_BOTTOM_RIGHT = 6
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_OBJECTRON_BOX_LANDMARK_BACK_TOP_RIGHT = 7
Global Const $MEDIAPIPE_AUTOIT_SOLUTIONS_OBJECTRON_BOX_LANDMARK_FRONT_TOP_RIGHT = 8

; mediapipe::autoit::solution_base::PacketDataType
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_STRING = 0
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_BOOL = 1
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_BOOL_LIST = 2
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_INT = 3
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_INT_LIST = 4
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_FLOAT = 5
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_FLOAT_LIST = 6
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_AUDIO = 7
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_IMAGE = 8
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_IMAGE_LIST = 9
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_IMAGE_FRAME = 10
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_PROTO = 11
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_PROTO_LIST = 12

; mediapipe::CalculatorGraph::GraphInputStreamAddMode
Global Const $MEDIAPIPE_CALCULATOR_GRAPH_GRAPH_INPUT_STREAM_ADD_MODE_WAIT_TILL_NOT_FULL = 0
Global Const $MEDIAPIPE_CALCULATOR_GRAPH_GRAPH_INPUT_STREAM_ADD_MODE_ADD_IF_NOT_FULL = 0

; mediapipe::InputCollection::InputType
Global Const $MEDIAPIPE_INPUT_COLLECTION_UNKNOWN = 0
Global Const $MEDIAPIPE_INPUT_COLLECTION_RECORDIO = 1
Global Const $MEDIAPIPE_INPUT_COLLECTION_FOREIGN_RECORDIO = 2
Global Const $MEDIAPIPE_INPUT_COLLECTION_FOREIGN_CSV_TEXT = 3
Global Const $MEDIAPIPE_INPUT_COLLECTION_INVALID_UPPER_BOUND = 4

; mediapipe::FieldDescriptorProto::Type
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_INVALID = 0
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_DOUBLE = 1
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_FLOAT = 2
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_INT64 = 3
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_UINT64 = 4
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_INT32 = 5
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_FIXED64 = 6
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_FIXED32 = 7
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_BOOL = 8
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_STRING = 9
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_GROUP = 10
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_MESSAGE = 11
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_BYTES = 12
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_UINT32 = 13
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_ENUM = 14
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_SFIXED32 = 15
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_SFIXED64 = 16
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_SINT32 = 17
Global Const $MEDIAPIPE_FIELD_DESCRIPTOR_PROTO_TYPE_SINT64 = 18

; mediapipe::LocationData::Format
Global Const $MEDIAPIPE_LOCATION_DATA_GLOBAL = 0
Global Const $MEDIAPIPE_LOCATION_DATA_BOUNDING_BOX = 1
Global Const $MEDIAPIPE_LOCATION_DATA_RELATIVE_BOUNDING_BOX = 2
Global Const $MEDIAPIPE_LOCATION_DATA_MASK = 3

; mediapipe::ImageFormat::Format
Global Const $MEDIAPIPE_IMAGE_FORMAT_UNKNOWN = 0
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGB = 1
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGBA = 2
Global Const $MEDIAPIPE_IMAGE_FORMAT_GRAY8 = 3
Global Const $MEDIAPIPE_IMAGE_FORMAT_GRAY16 = 4
Global Const $MEDIAPIPE_IMAGE_FORMAT_YCBCR420P = 5
Global Const $MEDIAPIPE_IMAGE_FORMAT_YCBCR420P10 = 6
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGB48 = 7
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGBA64 = 8
Global Const $MEDIAPIPE_IMAGE_FORMAT_VEC32F1 = 9
Global Const $MEDIAPIPE_IMAGE_FORMAT_VEC32F2 = 12
Global Const $MEDIAPIPE_IMAGE_FORMAT_LAB8 = 10
Global Const $MEDIAPIPE_IMAGE_FORMAT_SBGRA = 11

; mediapipe::InferenceCalculatorOptions::Delegate::Gpu::Api
Global Const $MEDIAPIPE_INFERENCE_CALCULATOR_OPTIONS_DELEGATE_GPU_ANY = 0
Global Const $MEDIAPIPE_INFERENCE_CALCULATOR_OPTIONS_DELEGATE_GPU_OPENGL = 1
Global Const $MEDIAPIPE_INFERENCE_CALCULATOR_OPTIONS_DELEGATE_GPU_OPENCL = 2

; mediapipe::InferenceCalculatorOptions::Delegate::Gpu::InferenceUsage
Global Const $MEDIAPIPE_INFERENCE_CALCULATOR_OPTIONS_DELEGATE_GPU_UNSPECIFIED = 0
Global Const $MEDIAPIPE_INFERENCE_CALCULATOR_OPTIONS_DELEGATE_GPU_FAST_SINGLE_ANSWER = 1
Global Const $MEDIAPIPE_INFERENCE_CALCULATOR_OPTIONS_DELEGATE_GPU_SUSTAINED_SPEED = 2

; mediapipe::GpuOrigin::Mode
Global Const $MEDIAPIPE_GPU_ORIGIN_DEFAULT = 0
Global Const $MEDIAPIPE_GPU_ORIGIN_CONVENTIONAL = 1
Global Const $MEDIAPIPE_GPU_ORIGIN_TOP_LEFT = 2

; mediapipe::AVDepthData::Accuracy
Global Const $MEDIAPIPE_AVDEPTH_DATA_UNDEFINED_ACCURACY = 0
Global Const $MEDIAPIPE_AVDEPTH_DATA_RELATIVE = 1
Global Const $MEDIAPIPE_AVDEPTH_DATA_ABSOLUTE = 2

; mediapipe::AVDepthData::Quality
Global Const $MEDIAPIPE_AVDEPTH_DATA_UNDEFINED_QUALITY = 0
Global Const $MEDIAPIPE_AVDEPTH_DATA_HIGH = 1
Global Const $MEDIAPIPE_AVDEPTH_DATA_LOW = 2

; mediapipe::ARCamera::TrackingState
Global Const $MEDIAPIPE_ARCAMERA_UNDEFINED_TRACKING_STATE = 0
Global Const $MEDIAPIPE_ARCAMERA_UNAVAILABLE = 1
Global Const $MEDIAPIPE_ARCAMERA_LIMITED = 2
Global Const $MEDIAPIPE_ARCAMERA_NORMAL = 3

; mediapipe::ARCamera::TrackingStateReason
Global Const $MEDIAPIPE_ARCAMERA_UNDEFINED_TRACKING_STATE_REASON = 0
Global Const $MEDIAPIPE_ARCAMERA_NONE = 1
Global Const $MEDIAPIPE_ARCAMERA_INITIALIZING = 2
Global Const $MEDIAPIPE_ARCAMERA_EXCESSIVE_MOTION = 3
Global Const $MEDIAPIPE_ARCAMERA_INSUFFICIENT_FEATURES = 4
Global Const $MEDIAPIPE_ARCAMERA_RELOCALIZING = 5

; mediapipe::ARPlaneAnchor::Alignment
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_UNDEFINED = 0
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_HORIZONTAL = 1
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_VERTICAL = 2

; mediapipe::ARPlaneAnchor::PlaneClassification
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_NONE = 0
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_WALL = 1
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_FLOOR = 2
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_CEILING = 3
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_TABLE = 4
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_SEAT = 5

; mediapipe::ARPlaneAnchor::PlaneClassificationStatus
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_UNKNOWN = 0
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_UNAVAILABLE = 1
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_UNDETERMINED = 2
Global Const $MEDIAPIPE_ARPLANE_ANCHOR_KNOWN = 3

; mediapipe::Object::Type
Global Const $MEDIAPIPE_OBJECT_UNDEFINED_TYPE = 0
Global Const $MEDIAPIPE_OBJECT_BOUNDING_BOX = 1
Global Const $MEDIAPIPE_OBJECT_SKELETON = 2

; mediapipe::Object::Method
Global Const $MEDIAPIPE_OBJECT_UNKNOWN_METHOD = 0
Global Const $MEDIAPIPE_OBJECT_ANNOTATION = 1
Global Const $MEDIAPIPE_OBJECT_AUGMENTATION = 2

; mediapipe::ScaleMode::Mode
Global Const $MEDIAPIPE_SCALE_MODE_DEFAULT = 0
Global Const $MEDIAPIPE_SCALE_MODE_STRETCH = 1
Global Const $MEDIAPIPE_SCALE_MODE_FIT = 2
Global Const $MEDIAPIPE_SCALE_MODE_FILL_AND_CROP = 3

; mediapipe::RotationMode::Mode
Global Const $MEDIAPIPE_ROTATION_MODE_UNKNOWN = 0
Global Const $MEDIAPIPE_ROTATION_MODE_ROTATION_0 = 1
Global Const $MEDIAPIPE_ROTATION_MODE_ROTATION_90 = 2
Global Const $MEDIAPIPE_ROTATION_MODE_ROTATION_180 = 3
Global Const $MEDIAPIPE_ROTATION_MODE_ROTATION_270 = 4

; mediapipe::LogicCalculatorOptions::Operation
Global Const $MEDIAPIPE_LOGIC_CALCULATOR_OPTIONS_AND = 0
Global Const $MEDIAPIPE_LOGIC_CALCULATOR_OPTIONS_OR = 1
Global Const $MEDIAPIPE_LOGIC_CALCULATOR_OPTIONS_XOR = 2
