#include-once
#include "mediapipe_interface.au3"

; PacketDataType
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_STRING = 0
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_BOOL = 1
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_BOOL_LIST = 2
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_INT = 3
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_INT_LIST = 4
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_FLOAT = 5
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_FLOAT_LIST = 6
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_AUDIO = 7
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_IMAGE = 8
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_IMAGE_LIST = 9
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_IMAGE_FRAME = 10
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_PROTO = 11
Global Const $MEDIAPIPE_AUTOIT_SOLUTION_BASE_PACKET_DATA_TYPE_PROTO_LIST = 12

; GraphInputStreamAddMode
Global Const $MEDIAPIPE_CALCULATOR_GRAPH_GRAPH_INPUT_STREAM_ADD_MODE_WAIT_TILL_NOT_FULL = 0
Global Const $MEDIAPIPE_CALCULATOR_GRAPH_GRAPH_INPUT_STREAM_ADD_MODE_ADD_IF_NOT_FULL = 0

; InputType
Global Const $MEDIAPIPE_INPUT_COLLECTION_UNKNOWN = 0
Global Const $MEDIAPIPE_INPUT_COLLECTION_RECORDIO = 1
Global Const $MEDIAPIPE_INPUT_COLLECTION_FOREIGN_RECORDIO = 2
Global Const $MEDIAPIPE_INPUT_COLLECTION_FOREIGN_CSV_TEXT = 3
Global Const $MEDIAPIPE_INPUT_COLLECTION_INVALID_UPPER_BOUND = 4

; Format
Global Const $MEDIAPIPE_LOCATION_DATA_GLOBAL = 0
Global Const $MEDIAPIPE_LOCATION_DATA_BOUNDING_BOX = 1
Global Const $MEDIAPIPE_LOCATION_DATA_RELATIVE_BOUNDING_BOX = 2
Global Const $MEDIAPIPE_LOCATION_DATA_MASK = 3

; Format
Global Const $MEDIAPIPE_IMAGE_FORMAT_UNKNOWN = 0
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGB = 1
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGBA = 2
Global Const $MEDIAPIPE_IMAGE_FORMAT_GRAY8 = 3
Global Const $MEDIAPIPE_IMAGE_FORMAT_GRAY16 = 4
Global Const $MEDIAPIPE_IMAGE_FORMAT_YCBCR420P = 5
Global Const $MEDIAPIPE_IMAGE_FORMAT_YCBCR420P10 = 6
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGB48 = 7
Global Const $MEDIAPIPE_IMAGE_FORMAT_SRGBA64 = 8
Global Const $MEDIAPIPE_IMAGE_FORMAT_VEC32F1 = 9
Global Const $MEDIAPIPE_IMAGE_FORMAT_VEC32F2 = 12
Global Const $MEDIAPIPE_IMAGE_FORMAT_LAB8 = 10
Global Const $MEDIAPIPE_IMAGE_FORMAT_SBGRA = 11

; Mode
Global Const $MEDIAPIPE_SCALE_MODE_DEFAULT = 0
Global Const $MEDIAPIPE_SCALE_MODE_STRETCH = 1
Global Const $MEDIAPIPE_SCALE_MODE_FIT = 2
Global Const $MEDIAPIPE_SCALE_MODE_FILL_AND_CROP = 3

; Mode
Global Const $MEDIAPIPE_ROTATION_MODE_UNKNOWN = 0
Global Const $MEDIAPIPE_ROTATION_MODE_ROTATION_0 = 1
Global Const $MEDIAPIPE_ROTATION_MODE_ROTATION_90 = 2
Global Const $MEDIAPIPE_ROTATION_MODE_ROTATION_180 = 3
Global Const $MEDIAPIPE_ROTATION_MODE_ROTATION_270 = 4

; Operation
Global Const $MEDIAPIPE_LOGIC_CALCULATOR_OPTIONS_AND = 0
Global Const $MEDIAPIPE_LOGIC_CALCULATOR_OPTIONS_OR = 1
Global Const $MEDIAPIPE_LOGIC_CALCULATOR_OPTIONS_XOR = 2
