module.exports = ({language}) => [
    // expose a vision property like in mediapipe python
    [`mediapipe.tasks.${ language }.vision.`, "", ["/Properties"], [
        ["mediapipe::tasks::vision::face_detector::FaceDetector", "FaceDetector", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::face_detector::FaceDetectorOptions", "FaceDetectorOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::components::containers::DetectionResult", "FaceDetectorResult", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::face_landmarker::FaceLandmarker", "FaceLandmarker", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::face_landmarker::FaceLandmarkerOptions", "FaceLandmarkerOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::face_landmarker::FaceLandmarkerResult", "FaceLandmarkerResult", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::face_landmarker::FaceLandmarksConnections", "FaceLandmarksConnections", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::gesture_recognizer::GestureRecognizer", "GestureRecognizer", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::gesture_recognizer::GestureRecognizerOptions", "GestureRecognizerOptions", "", ["/R", "=this", "/S"]],
        [`mediapipe::tasks::${ language }::vision::gesture_recognizer::GestureRecognizerResult`, "GestureRecognizerResult", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::hand_landmarker::HandLandmarker", "HandLandmarker", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::hand_landmarker::HandLandmarkerOptions", "HandLandmarkerOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::hand_landmarker::HandLandmarkerResult", "HandLandmarkerResult", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::hand_landmarker::HandLandmarksConnections", "HandLandmarksConnections", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::holistic_landmarker::HolisticLandmarker", "HolisticLandmarker", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::holistic_landmarker::HolisticLandmarkerOptions", "HolisticLandmarkerOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::holistic_landmarker::HolisticLandmarkerResult", "HolisticLandmarkerResult", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::image_classifier::ImageClassifier", "ImageClassifier", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::image_classifier::ImageClassifierOptions", "ImageClassifierOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::components::containers::ClassificationResult", "ImageClassifierResult", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::image_embedder::ImageEmbedder", "ImageEmbedder", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::image_embedder::ImageEmbedderOptions", "ImageEmbedderOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::components::containers::EmbeddingResult", "ImageEmbedderResult", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::image_segmenter::ImageSegmenter", "ImageSegmenter", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::image_segmenter::ImageSegmenterOptions", "ImageSegmenterOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::core::ImageProcessingOptions", "ImageProcessingOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::interactive_segmenter::InteractiveSegmenter", "InteractiveSegmenter", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::interactive_segmenter::InteractiveSegmenterOptions", "InteractiveSegmenterOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::interactive_segmenter::RegionOfInterest", "InteractiveSegmenterRegionOfInterest", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::ObjectDetector", "ObjectDetector", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::ObjectDetectorOptions", "ObjectDetectorOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::components::containers::DetectionResult", "ObjectDetectorResult", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::pose_landmarker::PoseLandmarker", "PoseLandmarker", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::pose_landmarker::PoseLandmarkerOptions", "PoseLandmarkerOptions", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::pose_landmarker::PoseLandmarkerResult", "PoseLandmarkerResult", "", ["/R", "=this", "/S"]],
        ["mediapipe::tasks::vision::pose_landmarker::PoseLandmarksConnections", "PoseLandmarksConnections", "", ["/R", "=this", "/S"]],

        ["mediapipe::tasks::vision::core::RunningMode", "RunningMode", "", ["/R", "=this", "/S"]],
    ], "", ""],
];
